config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  
  get   'contact',          to: 'messages#new'
  post  'contact',          to: 'messages#create'
  get   'about_us',         to: 'pages#about_us'
  post  'about_us',         to: 'pages#create_job'
  get   'privacy',          to: 'pages#privacy'
  
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'users/registrations' }

  resources :profiles,  only: [:show, :edit, :update, :destroy ]
  
end

app/models/message.rb
class Message
  include ActiveModel::Model

  attr_accessor :name, :email, :phone, :message, :speciality

  validates :name, presence: true
  validates_presence_of :message, :length => { 
    :maximum => 250,
    :tokenizer => lambda { |str| str.scan(/\w+/) },
    :too_long  => "Please limit your message to %{count} words"
  }
  
  validates :email, presence: true, 'valid_email_2/email': { disposable: true, mx: true }
  
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @soical_heading = true
    @message = Message.new
    @address = company_address
  end

  def create
    @soical_heading = true
    @address = company_address
    @message = Message.new message_params
    if @message.valid? && verify_recaptcha(model: @message)
      MessageMailer.contact(@message).deliver_now
      redirect_to contact_path
      flash[:success] = "We have received your message and will be in touch soon!"
    else
      flash[:alert] = "There was an error sending your message. Please try again."
      render :new
    end
  end

  private
    def message_params
      params.require(:message).permit(:name, :email, :phone, :message, :speciality)
    end

    def company_address
      if !ENV['COMPANY_ADDRESS_1'].blank?
        address = ENV['COMPANY_ADDRESS_1'] + "<br>"
        if !ENV['COMPANY_ADDRESS_2'].blank?
          address = address + ENV['COMPANY_ADDRESS_2'] + "<br>"
        end
        if !ENV['COMPANY_ADDRESS_CITY'].blank?
          address = address + ENV['COMPANY_ADDRESS_CITY'] + "<br>"
        end
        if !ENV['COMPANY_ADDRESS_COUNTRY'].blank?
          address = address + ENV['COMPANY_ADDRESS_COUNTRY'] + "<br>"
        end
        if !ENV['COMPANY_ADDRESS_POSTCODE'].blank?
          address = address + ENV['COMPANY_ADDRESS_POSTCODE']
        end
        return address
      end
    end

end

app/views/messages/new.html.erb
<%
 title "#{app_title} - Contact Us"
 meta_description "Contact Us - #{app_title}"
 heading "Contact Us"
 pclass "contact-page"
 heading_desc ""
%>



<div class="main">
  <div class="contact-content">
    <div class="container">
      <div class="row">
        <div class="col-md-5 ml-auto mr-auto">
          <h2 class="title">Send us a message</h2>
          <p class="description">
            You can contact us with anything related to our Products or Services. We'll get in touch with you as soon as possible.
            <br>
            <br>
          </p>
          <%= form_for @message, url: contact_url, id: "contact-form" do |f| %>
            <%= form_errors_for @message %>

            <%= f.hidden_field :speciality, value: 'none' %>
            <%= f.label :name %>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text"><i class="now-ui-icons users_circle-08"></i></span>
              </div>
              <%= f.text_field :name, autocomplete: "name", class: "form-control", placeholder: "Your Name....", "aria-label" => "Your Name..." %>
            </div>
            <%= f.label :email, "Email Address" %>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text"><i class="now-ui-icons ui-1_email-85"></i></span>
                </div>
                <%= f.email_field :email, autocomplete: "email", class: "form-control", placeholder: "Email Address...", "aria-label" => "Email Here..." %>
            </div>
            <%= f.label :phone %>
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text"><i class="now-ui-icons tech_mobile"></i></span>
              </div>
              <%= f.text_field :phone, autocomplete: "phone", class: "form-control", placeholder: "Phone Number...", "aria-label" => "Phone Number..." %>
            </div>
            <div class="form-group">
              <%= f.label :message, "Your message" %>
              <%= f.text_area :message, class: "form-control", id: "message", rows: 6 %>
              
            </div>
            <div class="input-group recaptcha">
              <%= recaptcha_tags %>
            </div>
            <div class="submit text-center">
              <%= f.submit "Contact Us", class: "btn btn-primary btn-raised btn-round" %>
            </div>
          <% end %>
        </div>
        <div class="col-md-5 ml-auto mr-auto">
          <div class="info info-horizontal mt-5">
            <% if !@address.nil? %>
              <div class="icon icon-primary">
                <i class="now-ui-icons location_pin"></i>
              </div>
              <div class="description">
                <h4 class="info-title">Find us at the office</h4>
                <p><%= @address.html_safe %>
                </p>
              </div>
            <% end %>
          </div>
          <div class="info info-horizontal">
            <% if ENV['COMPANY_CONTACT_PERSON'] %>
              <div class="icon icon-primary">
                <i class="now-ui-icons tech_mobile"></i>
              </div>
              <div class="description">
                <h4 class="info-title">Contact Support</h4>
                <p> <%= ENV['COMPANY_CONTACT_PERSON'] %>
                  <br><%= ENV['COMPANY_CONTACT_PHONE'] %>
                  <br><%= ENV['COMPANY_CONTACT_HOURS'] %>
                </p>
              </div>
              <% end %>
          </div>
          <div class="info info-horizontal">
            <% if ENV['COMPANY_LEGAL'] %>
              <div class="icon icon-primary">
                <i class="business_briefcase-24 now-ui-icons"></i>
              </div>
              <div class="description">
                <h4 class="info-title">Legal Information</h4>
                <p> <%= ENV['COMPANY_NAME'] %>.
                  <br><%= ENV['COMPANY_LEGAL_1'] %>
                  <br><%= ENV['COMPANY_LEGAL_2'] %>
                  <br><%= ENV['COMPANY_LEGAL_3'] %>
                  <br><%= ENV['COMPANY_LEGAL_4'] %>
                </p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div id="contactUs2Map" class="big-map"></div>



<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials[Rails.env.to_sym][:google][:maps_api_key] || 'insert_key' %>"></script>
<script type="text/javascript">
    $(document).ready(function() {
        // the body of this function is in assets/js/now-ui-kit.js
        nowuiKit.initContactUs2Map();
    });
</script>