config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  
  get   'contact',          to: 'messages#new'
  post  'contact',          to: 'messages#create'
  get   'about_us',         to: 'pages#about_us'
  post  'about_us',         to: 'pages#create_job'
  get   'privacy',          to: 'pages#privacy'
  
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'users/registrations' }

  resources :profiles,  only: [:show, :edit, :update, :destroy ]
  
end

app/views/layouts/nav/_footer.html.erb
<footer class="footer ">
  <div class="container">
    <nav>
      <ul>
        <li>
          <%= link_to "#{app_title} Repo", "https://github.com/wonderphil/base-app", target: :_blank %>
        </li>
        <li>
          <%= link_to "About Us", about_us_path %>
        </li>
        <li>
          <%= link_to "Contact Us", contact_path %>
        </li>
        <li>
          <%= link_to "T&C's and Privacy", privacy_path %>
        </li>
      </ul>
    </nav>
    <div class="copyright">
      &copy; <%= Time.now.year.to_s %> <%= app_title %> - All rights reserved
    </div>
  </div>
</footer>
<%= render 'layouts/clicky'  %>

app/views/layouts/nav/_header.html.erb
<nav class="navbar navbar-expand-lg bg-white fixed-top navbar-transparent" color-on-scroll="500">
  <div class="container">
    <!-- Add drop down menu to logo of nav bar
      <div class="dropdown button-dropdown">
        <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
          <span class="button-bar"></span>
          <span class="button-bar"></span>
          <span class="button-bar"></span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-header">Dropdown header</a>
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Separated link</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">One more separated link</a>
        </div>
      </div>
    -->
    <div class="navbar-translate">
      <%= link_to root_path, class: "navbar-brand", rel: "tooltip", title: app_title, "data-placement" =>"bottom"  do %>
         <%= app_title %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-bar bar1"></span>
        <span class="navbar-toggler-bar bar2"></span>
        <span class="navbar-toggler-bar bar3"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" data-nav-image="<%= image_path('blurred-image-1.jpg') %>" data-color="orange">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item <%= active_class?(root_path) %>">
          <%= link_to root_path, class: "nav-link" do %>
            Home
          <% end %>
        </li>
        <li class="nav-item <%= active_class?(contact_path) %>">
          <%= link_to contact_path, class: "nav-link" do %>
            Contact Us
          <% end %>
        </li>
        <li class="nav-item <%= active_class?(about_us_path) %>">
          <%= link_to about_us_path, class: "nav-link" do %>
            About Us
          <% end %>
        </li>
        <% if !user_signed_in? %>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "nav-link" do %>
              Sign Up
            <% end %>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <%= link_to "#", class: "nav-link dropdown-toggle", id: "navbarDropdownMenu", "data-toggle" => "dropdown" do %>
              <i class="now-ui-icons users_single-02"></i>
              <p>Profile</p>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to profile_path(current_user), class: "dropdown-item" do %>
                <i class="now-ui-icons users_circle-08"></i>
                View Profile
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <i class="now-ui-icons ui-1_simple-remove"></i>
                Logout
              <% end %>
            </div>
          </li>
        <% end %>
      
      
      </ul>
      <ul class="nav navbar-nav">
          <% if !user_signed_in? %>
            <li class="nav-item">
              <%=link_to new_user_session_path, class: "nav-link" do %>
                Sign in With:
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_twitter_omniauth_authorize_path, class: "nav-link" do %>
                <%= icon('fab', 'twitter') %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_facebook_omniauth_authorize_path, class: "nav-link" do %>
                <%= icon('fab', 'facebook-f') %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_amazon_omniauth_authorize_path, class: "nav-link" do %>
                <%= icon('fab', 'amazon') %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to user_google_omniauth_authorize_path, class: "nav-link" do %>
                <%= icon('fab', 'google') %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link" do %>
                <%= icon('fas', 'at') %>
              <% end %>
            </li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>