config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  
  get   'contact',          to: 'messages#new'
  post  'contact',          to: 'messages#create'
  get   'about_us',         to: 'pages#about_us'
  post  'about_us',         to: 'pages#create_job'
  get   'privacy',          to: 'pages#privacy'
  
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: 'users/registrations' }

  resources :profiles,  only: [:show, :edit, :update, :destroy ]
  
end

app/views/pages/about_us.html.erb
<%
 title "#{app_title} - About Us"
 meta_description "About Us - #{app_title}"
 heading "About Us!"
 pclass "signin-page"
 heading_desc "Meet the amazing team behind this project and find out more about how we work."
%>



<div class="section">
  <div class="about-description text-center">
    <div class="features-3">
      <div class="container">
        <div class="row">
          <div class="col-md-8 mr-auto ml-auto">
            <h2 class="title">Simpler. Smarter. Faster.</h2>
            <h4 class="description">We are a tech company at heart and we do want we do because we want to make life
              easier and better for everyone.</h4>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="info info-hover">
              <div class="icon icon-success icon-circle">
                <i class="now-ui-icons objects_globe"></i>
              </div>
              <h4 class="info-title">Asset Management</h4>
              <p class="description">Cross-account dashboards provide sophisticated reporting for enterprise.</p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="info info-hover">
              <div class="icon icon-info icon-circle">
                <i class="now-ui-icons education_atom"></i>
              </div>
              <h4 class="info-title">Resource Utilization</h4>
              <p class="description">CloudCheckr provides summary and detailed usage statistics for resources.</p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="info info-hover">
              <div class="icon icon-primary icon-circle">
                <i class="now-ui-icons tech_watch-time"></i>
              </div>
              <h4 class="info-title">Self-Healing</h4>
              <p class="description">CloudCheckr enables users to save money, time, and effort.</p>
            </div>
          </div>
        </div>
      </div>

      <div class="separator-line separator-primary"></div> #%>

      <div class="about-team team-4">
        <div class="container">
          <div class="row">
            <div class="col-md-8 ml-auto mr-auto text-center">
              <h2 class="title">We are nerd rockstars</h2>
              <h4 class="description">Techies at heart, out to change the world and making life just that little bit
                easier
                at each step.</h4>
            </div>
          </div>

          <div class="row">
            <div class="col-xl-6 col-lg-7 ml-auto mr-auto">
              <div class="card card-profile card-plain">
                <div class="row">
                  <div class="col-md-5">
                    <div class="card-image">
                      <%= image_tag ("olivia.jpg"), class: "img img-raised rounded" %>
                    </div>
                  </div>
                  <div class="col-md-7">
                    <div class="card-body">
                      <h4 class="card-title">Ella Evelyn</h4>
                      <h6 class="category">Air Crew Member</h6>
                      <p class="card-description">
                        Think in the morning. Act in the noon. Eat in the evening. Sleep in the night......
                      </p>
                      <div class="card-footer">
                        <%= link_to icon('fab', 'facebook'), "#", class: "btn btn-icon btn-neutral btn-facebook" %>
                        <%= link_to icon('fab', 'twitter'), "#", class: "btn btn-icon btn-neutral btn-twitter" %>
                        <%= link_to icon('fab', 'linkedin'), "#", class: "btn btn-icon btn-neutral btn-linkedin" %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-6 col-lg-7 ml-auto mr-auto">
              <div class="card card-profile card-plain">
                <div class="row">
                  <div class="col-md-5">
                    <div class="card-image">
                      <%= image_tag ("james.jpg"), class: "img img-raised rounded" %>
                    </div>
                  </div>
                  <div class="col-md-7">
                    <div class="card-body">
                      <h4 class="card-title">Mila Skylar</h4>
                      <h6 class="category">Architect</h6>
                      <p class="card-description">
                        Love cures people - both the ones who give it and the ones who receive it...
                      </p>
                      <div class="card-footer">
                        <%= link_to icon('fab', 'facebook'), "#", class: "btn btn-icon btn-neutral btn-facebook" %>
                        <%= link_to icon('fab', 'twitter'), "#", class: "btn btn-icon btn-neutral btn-twitter" %>
                        <%= link_to icon('fab', 'linkedin'), "#", class: "btn btn-icon btn-neutral btn-linkedin" %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="separator-line separator-primary"></div>

      <div class="about-contact">
        <div class="container">
          <div class="row">
            <div class="col-md-8 mr-auto ml-auto">
              <h2 class="text-center title">Want to work with us?</h2>
              <h4 class="text-center description">We are always on the look out for people that stand above the rest,
                who
                don't mind a start-up culture but also want to do things the right way.</h4>
              <%= form_for @job, url: about_us_url, id: "contact-form" do |f| %>
              <%= form_errors_for @job %>
              <%= f.hidden_field :phone, value: '00000' %>
              <div class="row">
                <div class="col-md-4">
                  <%= f.label :name, "Your Name" %>
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="now-ui-icons users_circle-08"></i></span>
                    </div>
                    <%= f.text_field :name, autocomplete: "name", class: "form-control", placeholder: "Your Name...." %>
                  </div>
                </div>
                <div class="col-md-4">
                  <%= f.label :email, "Your Email" %>
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="now-ui-icons ui-1_email-85"></i></span>
                    </div>
                    <%= f.email_field :email, autocomplete: "email", class: "form-control", placeholder: "Your Email...." %>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <%= f.label :speciality, "Speciality", class: "control-label" %>
                    <%= f.select(:speciality, ["I'm a Designer", "I'm a Developer", "I'm a Hero"], {}, {class: "selectpicker", "data-size" => "7", "data-style" => "btn btn-default btn-round mt-0", title: "Speciality"} ) %>

                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4 ml-auto mr-auto text-center">
                  <%= f.submit "Let's Talk", class: "btn btn-primary btn-round mt-4 btn-lg" %>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/pages/home.html.erb
<%
 title "#{app_title} - Welcome"
 meta_description app_title
 heading 'This is our great template.'
 pclass "signin-page"
 heading_desc "Welcome to Rails 5 / Devise template"
%>


<div class="section section-about-us">
  <div class="container">
    <div class="row">
      <div class="col-md-8 ml-auto mr-auto text-center">
        <h2 class="title">Template Details</h2>
        <h5 class="description">
          Welcome to the base app. To start make sure you first add all the details in .env file.<br>
          If hosting in docker and not using docker compose make sure you have all the environment varibles set.<br>
          Next thing to sort out is the secrets file, in the secrets file you have all the api keys required for social logins.<br>
        </h5>
      </div>
    </div>
    <div class="separator separator-primary"></div>
    <div class="section-story-overview">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <h2 class="title">.env File</h2>
          <pre>
                <code class="yaml">
                  COMPOSE_PROJECT_NAME=base_app
                  COMPANY_NAME=Philip Davies
                  LOG_LEVEL=debug
                  WORKER_PROCESSES=1
                  LISTEN_ON=0.0.0.0:8080
                  RACK_TIMEOUT_SERVICE_TIMEOUT=30
                  POSTGRES_USER=rails
                  POSTGRES_PASSWORD=rails
                  RAILS_MAX_THREADS=5
                  DB_HOST=db.local
                  DB_USER=rails
                  DB_DATABASE=base_app
                  DB_PASS=rails
                  RAILS_ENV=development
                  SMTP_ADDRESS=smtp.gmail.com
                  SMTP_PORT=587
                  SMTP_DOMAIN=gmail.com
                  SMTP_AUTH=plain
                  SMTP_ENABLE_STARTTLS_AUTO=true
                  ACTION_MAILER_HOST=localhost:8080
                  ACTION_MAILER_DEFAULT_FROM=someone@gmail.com
                  ACTION_MAILER_DEFAULT_TO=you@gmail.com
                  REDIS_CACHE_NAMESPACE=cache
                  ACTIVE_JOB_QUEUE_PREFIX=base-app:jobs
                  ACTION_CABLE_ALLOWED_REQUEST_ORIGINS=http:\/\/localhost*
                  CLICKY_SITE_ID=101152957
                  SKIP_PSQL_AVAILABLE=false 
                  SKIP_DB_SETUP=true
                  SKIP_DB_RESET=true
                  SKIP_DB_SEED=true
                  SKIP_DB_DEPLOY=false
                  SKIP_APP_START=false
                </code>
              </pre>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <h2 class="title">Secrets File</h2>
          <pre>
                <code class="yaml">
                  secret_key_base:
      
                  development:
                    database:
                      pass: rails
                    amazon:
                      client_id:
                      client_secret:
                    twitter:
                      api_key: 
                      api_secret:
                    google:
                      client_id:
                      client_secret:
                      recaptcha_site_key:
                      recaptcha_secret_key:
                    facebook:
                      facebook_key:
                      facebook_secret:
                    smtp:
                      username: someone@gmail.com
                      password: anything
                    redis:
                      password: yourpassword


                test:
                  database:
                    pass: rails
                  amazon:
                    client_id:
                    client_secret:
                  twitter:
                    api_key:
                    api_secret:
                  google:
                    client_id:
                    client_secret:
                    recaptcha_site_key:
                    recaptcha_secret_key:
                  facebook:
                    facebook_key:
                    facebook_secret:
                  smtp:
                    username: someone@gmail.com
                    password: anything
                  redis:
                    password: yourpassword

                  production:
                    database:
                      pass: somethingbetterthenthis!!!
                    amazon:
                      client_id: 
                      client_secret:
                    twitter:
                      api_key: 
                      api_secret:
                    google:
                      client_id:
                      client_secret:
                      recaptcha_site_key:
                      recaptcha_secret_key:
                    facebook:
                      facebook_key:
                      facebook_secret:
                    smtp:
                      username: someone@gmail.com
                      password: anything
                    redis:
                      password: yourpassword
                </code>
              </pre>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/pages/privacy.html.erb
<%
 title "#{app_title} - Privacy & Terms Of Use"
 meta_description "Privacy & Terms Of Use - #{app_title}"
 heading "Privacy & Terms Of Use"
 pclass "signin-page"
%>

<div class="section section-about-us">
  <div class="container">
    <div class="row">
      <div class="col-md-8 ml-auto mr-auto text-center">
        <h2 class="title">Effective date: November 2018</h2>
        <h5 class="description">
          <p><%= ENV["COMPANY_NAME"] || ENV["COMPOSE_PROJECT_NAME"] %> ("us", "we", or "our") operates the <%= link_to request.host %> website (the "Service").</p>
          <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
          <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. 
            Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from <%= link_to "Privacy & Terms", privacy_path %>
          </p>
        </h5>
        <h2 class="title">Information Collection And Use</h2>
        <h5 class="description">
          <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
        </h5>
        <h2 class="title">Types of Data Collected</h2>
        <h3 class="title">Personal Data</h3>
        <h5 class="description">
          <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). 
            Personally identifiable information may include, but is not limited to:</p>
          <ul class="privacy">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </ul>
        </h5>
        <h3 class="title">Usage Data</h3>
        <h5 class="description">
          <p>We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's 
            Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, 
            the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
        </h5>
        <h3 class="title">Tracking & Cookies Data</h3>
        <h5 class="description">
          <p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>
            <p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. 
              Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
            <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
            <p>Examples of Cookies we use:</p>
            <ul class="privacy">
              <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
              <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
              <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
            </ul>
        </h5>
        <h2 class="title">Use of Data</h2>
        <h5 class="description">
          <p><%= ENV["COMPANY_NAME"]%> uses the collected data for various purposes:</p>    
          <ul class="privacy">
            <li>To provide and maintain the Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer care and support</li>
            <li>To provide analysis or valuable information so that we can improve the Service</li>
            <li>To monitor the usage of the Service</li>
            <li>To detect, prevent and address technical issues</li>
          </ul>
        </h5>
        <h2 class="title">Transfer Of Data</h2>
        <h5 class="description">
          <p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, 
            country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
          <p>If you are located outside United Kingdom and choose to provide information to us, please note that we transfer the data, including Personal Data, to United Kingdom and process it there.</p>
          <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
          <p><%= ENV["COMPANY_NAME"]%> will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy 
            and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
            </p>
        </h5>
        <h2 class="title">Disclosure Of Data</h2>
        <h3 class="title">Legal Requirements</h3>
        <h5 class="description">
          <p><%= ENV["COMPANY_NAME"]%> may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul class="privacy">
            <li>To comply with a legal obligation</li>
            <li>To protect and defend the rights or property of <%= ENV["COMPANY_NAME"]%></li>
            <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>To protect the personal safety of users of the Service or the public</li>
            <li>To protect against legal liability</li>
          </ul>
        </h5>
        <h2 class="title">Security Of Data</h2>
        <h5 class="description">
          <p>
            The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic
            storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </p>
        </h5>
        <h2 class="title">Service Providers</h2>
        <h5 class="description">
          <p>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, 
            to perform Service-related services or to assist us in analyzing how our Service is used.</p>
          <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
          </p>
        </h5>
        <h2 class="title">Analytics</h2>
        <h5 class="description">
          <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>    
          <ul class="privacy">
            <li>
                <p><strong>Google Analytics</strong></p>
                <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor 
                  the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
                <p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. 
                  The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</p>
                <p>For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: 
                  <%= link_to "Google Privacy & Terms", "https://policies.google.com/privacy?hl=en", target: :_blank %>
                </p>
            </li>
            <li>
                <p><strong>Clicky</strong></p>
                <p>Clicky is a web analytics service. Read the Privacy Policy for Clicky here: <%= link_to "Clicky Terms", "https://clicky.com/terms", target: :_blank %></p>
            </li>
          </ul>
        </h5>
        <h2 class="title">Links To Other Sites</h2>
        <h5 class="description">
          <p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. 
            We strongly advise you to review the Privacy Policy of every site you visit.</p>
          <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
        </h5>
        <h2 class="title">Children's Privacy</h2>
        <h5 class="description">
          <p>Our Service does not address anyone under the age of 18 ("Children").</p>
          <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. 
            If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. 
            If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
          </p>
        </h5>
        <h2 class="title">Changes To This Privacy Policy</h2>
        <h5 class="description">
          <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
          <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
        </h5>
        <h2 class="title">Contact Us</h2>
        <h5 class="description">
          <p>If you have any questions about this Privacy Policy, please contact us:</p>
          <ul class="privacy">
            <li>By visiting our contact page: <%= link_to "Contact Us", contact_path %></li>
          </ul>
        </h5>
      </div>
    </div>
  </div>
</div>